### ISSUE TITLE
Parameter specified with no associated flag

### ISSUE THREAD

**Issue by Inrixia** [mattlyons0/Rsync-Snapshot#35]
![image](https://user-images.githubusercontent.com/6373693/67100163-b10d7a00-f21b-11e9-9946-f20388285f14.png)
When using this module recently I have been getting this error when using excludes... Do you know why this is and how I could fix it?

**Comment by Inrixia** [comment]
Seems too only occur for files that are marked to be excluded within the root dir of the backup...

**Comment by mattlyons0** [comment]
It looks like your shell is attempting to parse the globs and is parsing `*.log*` to `hs_error_pid25419.log` (one of the file matches for the glob).

This can be fixed by simply quoting the glob `--exclude "*.log*"`. If you have a lot of excludes and want to write them to a file you could use `--excludeFile myExcludeFile.txt` where `myExcludeFile.txt` is a list of the globs to exclude [example exclude file](https://github.com/mattlyons0/Rsync-Snapshot/blob/master/data/defaultExclude.txt)

**Comment by Inrixia** [comment]
Ah yes, I was using.
```javascript
if (mS.excludes.length > 0) mS.excludes.forEach(exclude => excludes += `--exclude ${exclude} `)
```
Ill test with "" and see if it fixes it. Thanks

**Comment by Inrixia** [comment]
Sorry for the delay in closing this :) Finally pushed the changes to live and its fixed. Thanks for the help!
